=== Shehab8K/xml/Lab3/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2023 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="address">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="street"/>
				<xs:element ref="building-number"/>
				<xs:element ref="region"/>
				<xs:element ref="city"/>
				<xs:element ref="country"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="addresses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="address"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="building-number">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="30"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="city">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Alexandria"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="contract">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="employee" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="country">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Egypt"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="email">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Malek@gmail.com"/>
				<xs:enumeration value="Mariam@gmail.com"/>
				<xs:enumeration value="Shehab@gmail.com"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="employee">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="phones"/>
				<xs:element ref="email"/>
				<xs:element ref="addresses"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Malek"/>
				<xs:enumeration value="Mariam"/>
				<xs:enumeration value="Shehab"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="phone">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_phone">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="home"/>
								<xs:enumeration value="mobile"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="phones">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="phone" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="region">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Flemng"/>
				<xs:enumeration value="sidi Beshr"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="street">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Alexander"/>
				<xs:enumeration value="el fath"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:simpleType name="ST_phone">
		<xs:restriction base="xs:int">
			<xs:enumeration value="1152254433"/>
			<xs:enumeration value="1234566433"/>
			<xs:enumeration value="1252254433"/>
			<xs:enumeration value="35844750"/>
			<xs:enumeration value="42844750"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Shehab8K/xml/Lab3/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="emp.xsl"?>
<contract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/ITI/XML/Lab3/employee.xsd">
	<employee>
		<name>Shehab</name>
		<phones>
			<phone type="mobile">01152254433</phone>
			<phone type="home">035844750</phone>
		</phones>
		<email>Shehab@gmail.com</email>
		<addresses>
			<address>
				<street>el fath</street>
				<building-number>30</building-number>
				<region>Flemng</region>
				<city>Alexandria</city>
				<country>Egypt</country>
			</address>
		</addresses>
	</employee>
	<employee>
		<name>Mariam</name>
		<phones>
			<phone type="mobile">01252254433</phone>
			<phone type="home">042844750</phone>
		</phones>
		<email>Mariam@gmail.com</email>
		<addresses>
			<address>
				<street>Alexander</street>
				<building-number>30</building-number>
				<region>sidi Beshr</region>
				<city>Alexandria</city>
				<country>Egypt</country>
			</address>
		</addresses>
	</employee>
	<employee>
		<name>Malek</name>
		<phones>
			<phone type="mobile">01234566433</phone>
			<phone type="home">035844750</phone>
		</phones>
		<email>Malek@gmail.com</email>
		<addresses>
			<address>
				<street>Alexander</street>
				<building-number>30</building-number>
				<region>sidi Beshr</region>
				<city>Alexandria</city>
				<country>Egypt</country>
			</address>
		</addresses>
	</employee>
</contract>
